# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hackthepress"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexandre Girard"]
  s.date = "2012-01-17"
  s.description = "This rubygem contains necessary method to parse and analyse data from Hack The Press event"
  s.email = "hackthepress@alexgirard.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/hackthepress.rb",
    "lib/hackthepress/deputy.rb",
    "lib/hackthepress/grapher.rb",
    "lib/hackthepress/parser.rb",
    "spec/deputy_spec.rb",
    "spec/grapher_spec.rb",
    "spec/hackthepress_spec.rb",
    "spec/parser_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/tetalab/hackthepress"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Hack the Press rubygem for Tetalab data experiement"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<data_mapper>, ["= 1.2.0"])
      s.add_runtime_dependency(%q<nokogiri>, ["= 1.5.0"])
      s.add_runtime_dependency(%q<googlecharts>, ["= 1.6.8"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<data_mapper>, ["= 1.2.0"])
      s.add_dependency(%q<nokogiri>, ["= 1.5.0"])
      s.add_dependency(%q<googlecharts>, ["= 1.6.8"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<data_mapper>, ["= 1.2.0"])
    s.add_dependency(%q<nokogiri>, ["= 1.5.0"])
    s.add_dependency(%q<googlecharts>, ["= 1.6.8"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

